name: Build, test and publish

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore SolTechnology.Time.sln
    - name: Build
      run: dotnet build SolTechnology.Time.sln --no-restore
    - name: Test
      shell: pwsh
      run: |
           .\.github\runTests.ps1
   
    - name: Pack SolTechnology.DateTimeZone
      run: dotnet pack -c Release -o . ./src/SolTechnology.Time/SolTechnology.Time.csproj


    - name: Publish all nuget packages
      run: dotnet nuget push *.nupkg -k ${{secrets.NUGET_API_KEY}} -s https://api.nuget.org/v3/index.json --skip-duplicate